export const resolutions = {
  r2160p: "4K UHD - 2160p",
  r1440p: "QHD - 1440p",
  r1080p: "FHD - 1080p",
  r720p: "HD - 720p",
  r576p: "SD - 576p",
  r480p: "SD - 480p",
  r360p: "LD - 360p",
  r240p: "LD - 240p",
  unknown: "Unknown",
} as const;

export const serverResolutionMap: Record<number, keyof typeof resolutions> = {
  9: "r2160p",
  7: "r1440p",
  6: "r1080p",
  5: "r720p",
  4: "r576p",
  3: "r480p",
  2: "r360p",
  1: "unknown",
};

export const languagesEmojis = {
  multi: "🌎",
  en: "🇬🇧",
  ja: "🇯🇵",
  zh: "🇨🇳",
  ru: "🇷🇺",
  ar: "🇸🇦",
  pt: "🇵🇹",
  es: "🇪🇸",
  fr: "🇫🇷",
  de: "🇩🇪",
  it: "🇮🇹",
  ko: "🇰🇷",
  hi: "🇮🇳",
  bn: "🇧🇩",
  pa: "🇵🇰",
  mr: "🇮🇳",
  gu: "🇮🇳",
  ta: "🇮🇳",
  te: "🇮🇳",
  kn: "🇮🇳",
  ml: "🇮🇳",
  th: "🇹🇭",
  vi: "🇻🇳",
  id: "🇮🇩",
  tr: "🇹🇷",
  he: "🇮🇱",
  fa: "🇮🇷",
  uk: "🇺🇦",
  el: "🇬🇷",
  lt: "🇱🇹",
  lv: "🇱🇻",
  et: "🇪🇪",
  pl: "🇵🇱",
  cs: "🇨🇿",
  sk: "🇸🇰",
  hu: "🇭🇺",
  ro: "🇷🇴",
  bg: "🇧🇬",
  sr: "🇷🇸",
  hr: "🇭🇷",
  sl: "🇸🇮",
  nl: "🇳🇱",
  da: "🇩🇰",
  fi: "🇫🇮",
  sv: "🇸🇪",
  no: "🇳🇴",
  ms: "🇲🇾",
  la: "💃🏻",
} as const;

export const languageNames = {
  multi: "Multi",
  en: "English",
  ja: "Japanese",
  zh: "Chinese",
  ru: "Russian",
  ar: "Arabic",
  pt: "Portuguese",
  es: "Spanish",
  fr: "French",
  de: "German",
  it: "Italian",
  ko: "Korean",
  hi: "Hindi",
  bn: "Bengali",
  pa: "Punjabi",
  mr: "Marathi",
  gu: "Gujarati",
  ta: "Tamil",
  te: "Telugu",
  kn: "Kannada",
  ml: "Malayalam",
  th: "Thai",
  vi: "Vietnamese",
  id: "Indonesian",
  tr: "Turkish",
  he: "Hebrew",
  fa: "Persian",
  uk: "Ukrainian",
  el: "Greek",
  lt: "Lithuanian",
  lv: "Latvian",
  et: "Estonian",
  pl: "Polish",
  cs: "Czech",
  sk: "Slovak",
  hu: "Hungarian",
  ro: "Romanian",
  bg: "Bulgarian",
  sr: "Serbian",
  hr: "Croatian",
  sl: "Slovenian",
  nl: "Dutch",
  da: "Danish",
  fi: "Finnish",
  sv: "Swedish",
  no: "Norwegian",
  ms: "Malay",
  la: "Latino",
} as const;

export const DEBRID_SERVICES = {
  realdebrid: {
    name: "Real-Debrid",
    apiKeyUrl: "https://real-debrid.com/apitoken",
    referralUrl: "http://real-debrid.com/?id=16161532",
    helpText: "Format: `api-key`",
  },
  torbox: {
    name: "TorBox",
    apiKeyUrl: "https://torbox.app/settings",
    referralUrl: "https://torbox.app/subscription?referral=1ffb2238-1c5f-402e-a2ce-3d7a86c52d02",
    helpText: "Format: `api-key`",
  },
  alldebrid: {
    name: "All-Debrid",
    apiKeyUrl: "https://alldebrid.com/apikeys",
    referralUrl: null,
    helpText: "Format: `api-key`",
  },
  debridlink: {
    name: "Debrid-Link",
    apiKeyUrl: "https://debrid-link.com/webapp/apikey",
    referralUrl: "https://debrid-link.fr/id/G7mli",
    helpText: "Format: `api-key`",
  },
  premiumize: {
    name: "Premiumize",
    apiKeyUrl: "https://premiumize.me/account",
    referralUrl: null,
    helpText: "Format: `api-key`",
  },
  debrider: {
    name: "Debrider",
    apiKeyUrl: "https://debrider.app/dashboard/account",
    referralUrl: null,
    helpText: "Format: `api-key`",
  },
  easydebrid: {
    name: "EasyDebrid",
    apiKeyUrl: "https://paradise-cloud.com/products/easydebrid",
    referralUrl: null,
    helpText: "Format: `api-key`",
  },
  offcloud: {
    name: "Offcloud",
    apiKeyUrl: "https://offcloud.com",
    referralUrl: null,
    helpText: "Format: `email:password`",
  },
  pikpak: {
    name: "PikPak",
    apiKeyUrl: "https://mypikpak.com",
    referralUrl: null,
    helpText: "Format: `email:password`",
  },
} as const;
